spring:
  application:
    name: open_the_world
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  codec:
    max-in-memory-size: 500KB

amazonProperties:
  endpointUrl: https://storage.yandexcloud.net
  bucketName: open-the-world-bucket

geo:
  earthRadius: 6378137
  maxDistance: 100

yandexApi:
  foundationModelsUri: ${FOUNDATION_MODELS_URI:https://llm.api.cloud.yandex.net/foundationModels/v1/completion}
  token: ${GPT_TOKEN:AQVNxf5dzK3AAB5MmmB1nL8OISV5gXyTdE3ej-sH}
  modelUri: ${GPT_MODEL_URI:gpt://b1go9ij03gceo2iisf9b/yandexgpt}

openStreetMap:
  baseUrl: https://routing.openstreetmap.de/
  carEndpoint: routed-car/route/v1/driving/
  footEndpoint: routed-foot/route/v1/driving/
  bikeEndpoint: routed-bike/route/v1/driving/

overpassTurbo:
  baseUrl: https://overpass-api.de/api/interpreter

flickr:
  baseUrl: https://www.flickr.com/services/rest/
  apiKey: 1ba0b8648fec28623eebe3b210b24d7d

quest:
  generateQuestsFixedRate: 600000

websocket:
  storage:
    fixedDelay:
      in:
        milliseconds: 3600000
