spring:
  liquibase:
    enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI_OAUTH2:http://localhost:8082/realms/hits-project}
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI_OAUTH2:http://localhost:8082/realms/hits-project}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: ${CLIENT_ID_OAUTH2:users-app}
            client-secret: ${CLIENT_SECRET_OAUTH2:12345678}
            scope:
              - openid
              - microprofile-jwt
              - profile

  jooq:
    sql-dialect: postgres

hits-project:
  users-realm: ${REALM_NAME:hits-project}
  services:
    users:
      uri: ${KEYCLOAK_URI:http://localhost:8082}

authServer:
  authorizationUrl: http://158.160.85.50:8082/realms/hits-project/protocol/openid-connect/auth
  tokenUrl: http://158.160.85.50:8082/realms/hits-project/protocol/openid-connect/token
  refreshUrl: http://158.160.85.50:8082/realms/hits-project/protocol/openid-connect/token

server:
  port: 8080