spring:
  application:
    name: open_the_world
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB

amazonProperties:
  endpointUrl: https://storage.yandexcloud.net
  bucketName: open-the-world-bucket

geo:
  earthRadius: 6378137
  maxDistance: 100

websocket:
  storage:
    fixedDelay:
      in:
        milliseconds: 3600000
